### ISSUE TITLE
rawToRgb is not a function

### ISSUE THREAD

**Issue by m-mohr** [GeoTIFF/georaster-layer-for-leaflet#120]
**Describe the bug**
I'm trying to visualize the eu_pasture.tiff from the test-data repo in stac-layer. 
It results in an error message: 

> TypeError: r.rawToRgb is not a function

This only happens if I set the mins/maxs/ranges.

**Expected behavior**
No error ;-)

**Comment by DanielJDufour** [comment]
rawToRgb comes from [pixel-utils](https://github.com/danieljdufour/pixel-utils)

I think it might be an issue with what import system (CJS/TS/ESM) pixel-utils, georaster-layer-for-leaflet and stac-layer uses.

But definitely fixable.  I'll look into it.

**Comment by m-mohr** [comment]
Ah it seems setting calcStats to false disabled setting this.rawToRgb...

**Comment by m-mohr** [comment]
See #121

**Comment by DanielJDufour** [comment]
Would it be possible to set the mins, maxs and ranges on the `georaster` object and not the `currentStats` object?  Technically, the mins, maxs, ranges are a part of the public georaster definition (https://github.com/geotiff/georaster#required-properties) whereas currentStats isn't technically public (so it doesn't have the same sort of commitment for support/backwards compatability across major version upgrades).

I think this might do it:
```js
    georaster.mins = [];
    georaster.maxs = [];
    georaster.ranges = [];
    for (let i = 0; i < georaster.numberOfRasters; i++) {
      let { minimum, maximum } = asset.getMinMaxValues(i);
      georaster.mins.push(minimum);
      georaster.maxs.push(maximum);
      georaster.ranges.push(maximum - minimum);
    }
```

Let me know if you think this might work.  Honestly, before STAC existed, I didn't envision statistics being available for geotiffs accessed through range requests.  It's a definite oversight on my part and improvements to georaster and georaster-layer-for-leaflet are definitely required regardless of the approach we take here.

Open to your thoughts :-)

**Comment by m-mohr** [comment]
Thanks! I guess that should work, will check. I think I only used currentStats based on a proposal from you :-)

**Comment by DanielJDufour** [comment]
oof. sorry about that.

**Comment by m-mohr** [comment]
I gave it a shot, but it seems that there's still an error:

```
TypeError: r is not a function
    Se convert-single-str.js:3
    pixelValuesToColorFn georaster-layer-for-leaflet.js:157
    getColor georaster-layer-for-leaflet.js:877
    e georaster-layer-for-leaflet.js:718
...
```

It looks like scale in the convert_raw_one_band_pixel_to_rgb_str function is sometimes not defined?!

**Comment by m-mohr** [comment]
It doesn't throw an error if I fill the mins/max/ranges with the values for the first band (but then it doesn't show an image/it's transparent).

**Comment by m-mohr** [comment]
Okay, so I debugged a bit into it. 

After merging #121, it works for me if I set layer.currentStats. It does not work if I assign directly to the georaster object.

**Comment by m-mohr** [comment]
Okay, nevermind :D I assigned the values too late to the georaster object. Seems to work now.

**Comment by m-mohr** [comment]
oh no! I just figured that I was working on 3.10.0. #121 was not released yet, right? @DanielJDufour
